# Generated by Django 3.1.5 on 2021-01-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210119_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_avatar',
            field=models.CharField(default='https://www.kindpng.com/picc/m/105-1055656_account-user-profile-avatar-avatar-user-profile-icon.png', max_length=220),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_URL',
            field=models.CharField(max_length=200),
        ),
    ]
